### ISSUE TITLE
Revisiting PMAPS IO

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#165] opened 2017-03-10 09:53 UTC
Recent development has made clear that we need to handle the IO of PMAPS in a consistent way. 

In fact, PMAPS IO is an interesting problem because it is the first case in IC where we need to handle a persistent representation that is different from the transient representation of the data.  Before PMAPS the transient representation is identical to the persistent representation (arrays of waveforms).

To summarise, the (almost) agreed transient representation of the PMAPS is:

S1/S2 = {event: {peak: namedtudple('t','E')}} where t and E are np arrays.

S2Si = {event:{peak:{nsipm:[E]}}} where E is a np.array of energies (not sparse, e.g, zeros included)

Do we all agree on this? The current representation of S2Si is different:
S2Si = {event:{peak:[nsipm, ([N],[E])]}}

where [N] is a vector of samples and E is a vector of energies sparse (e.g, zeros not included). HOWEVER, we can get rid of [N] by writing the zeros in [E] (thus there is a direct mapping in time with the S2), at very little cost, since after SiPM zero suppression, the vectors are very small. In addition, we can substitute the list by another dictionary, as suggested by @gonzaponte, a more consistent and elegant rep. 

AGREED?

Coming to persistent representation, we use pytables. The relevant fields are:

```
class S12(tb.IsDescription):
    """Store for a S1/S2
    The table maps a S12:
    peak is the index of the S12 dictionary, running over the number of peaks found
    time and energy of the peak.
    """
    event  = tb.Int32Col(pos=0)
    evtDaq = tb.Int32Col(pos=1)
    peak   = tb.UInt8Col(pos=2)  # peak number
    time   = tb.Float32Col(pos=3) # time in ns
    ene    = tb.Float32Col(pos=4) # energy in pes


class S2Si(tb.IsDescription):
    """Store for a S2Si
    The table maps a S2Si
    peak is the same than the S2 peak
    nsipm gives the SiPM number
    only energies are stored (times are defined in S2)
    """
    event   = tb.Int32Col(pos=0)
    evtDaq  = tb.Int32Col(pos=1)
    peak    = tb.UInt8Col(pos=2)  # peak number
    nsipm   = tb.Int16Col(pos=3)  # sipm number
    nsample = tb.Int16Col(pos=4) # sample number
    ene     = tb.Float32Col(pos=5) # energy in pes
```

In the tables above, we distinguish between event and evetDaq. This is due to historical reasons, since in the real data the events always come with a number, while in the MC we did not have such unique number.

This is totally confusing and should be solved like this:

1) MC events should also come with a unique number.
2) The field evtDaq should be eliminated. In this way, we only have one event number to care for, the one that goes both to the persistent and transient rep of the data.

Agree?

I will continue the discussion later. Please, let's agree on the issues above. Also, @gonzaponte, @jacg, @neuslopez, @jmbenlloch take a look to my branch PmapWriter, for a working example of a writer. The writer includes a test, but care has to be taken when modifying Irene to add it (I will do it shortly). 

More soon.

**Comment by gonzaponte** [comment] 2017-03-10 10:12
- I agree with the transient representation. Just to clarify, I don't think we need a named tuple in this scenario.

- Regarding the persistent one, the "evt" field is the numbering ***within*** a file, is that correct? If so, it may be useful. In the current df_to_dict functions there is an argument "max_events" assumed to go from 0 to n_events_produced (not necessarily equal to n_events_stored_in_file). If we remove this field, it may become tricky to select the same events in s1s and s2s dicts when asking for a reduced subset (because, max_events will depend on the file we are using). Of course, we can always remove this argument and return all pmaps, but I don't know if it is a good idea.

- Maybe a stupid question... Why not storing the zeros in disk directly? Isn't it cheaper to store a few extra zeros than adding a whole new column (nsample)?

**Comment by jjgomezcadenas** [comment] 2017-03-10 10:34
>I agree with the transient representation. Just to clarify, I don't think we need a named tuple in this scenario.

I think the named tuple is nice to access to t and E fields in the array by "dot" (S1[peak].E). And is free. 

>Regarding the persistent one, the "evt" field is the numbering within a file, is that correct? If so, it may be useful. In the current df_to_dict functions there is an argument "max_events" assumed to go from 0 to n_events_produced (not necessarily equal to n_events_stored_in_file). If we remove this field, it may become tricky to select the same events in s1s and s2s dicts when asking for a reduced subset (because, max_events will depend on the file we are using). Of course, we can always remove this argument and return all pmaps, but I don't know if it is a good idea.

This is precisely what I want to get rid of. Since we are storing stuff in tables (which have an entry index) and representing stuff in dictionaries (by key) we don't need to store the event-within-a-file in the tables or in the dictionaries. Think that eventually we want to combine different PMAP files and thus we need all the events to be unique (also we need a unique number to trace them back to raw waveforms if needed). We can always ask the PMAP readers to read "10 events" but we should have an unique event number.

>Maybe a stupid question... Why not storing the zeros in disk directly? Isn't it cheaper to store a few extra zeros than adding a whole new column (nsample)?

Not stupid! This is exactly what I am proposing. We store the E samples in S2Si  wether they are zeros or not, and forget about the samples!

**Comment by gonzaponte** [comment] 2017-03-10 10:52
> I think the named tuple is nice to access to t and E fields in the array by "dot" (S1[peak].E). And is free.

I was referring to the S2Si, which contains only "E"

> We can always ask the PMAP readers to read "10 events" but we should have an unique event number.

The problem is that, because S1 and S2 are read independently, it is not easy to get the same events. For example: if you tell the function to read 5 events from s1s, it will you return (for instance) events number [0, 1, 3, 7, 8], while if you do the same with s2s you get something like [0, 1, 2, 3, 4]. This can be handled by a PMapReader, that reads s1s and s2s simultaneously, but needs to be taken into account. Agreed?

> Not stupid! This is exactly what I am proposing. We store the E samples in S2Si wether they are zeros or not, and forget about the samples!

Maybe I misunderstood you. I thought you were referring to the transient representation only. I was referring also to the persistent one.

**Comment by jjgomezcadenas** [comment] 2017-03-10 15:51
> On 10 Mar 2017, at 11:52, Gonzalo <notifications@github.com> wrote:
> 
> I think the named tuple is nice to access to t and E fields in the array by "dot" (S1[peak].E). And is free.
> 
> I was referring to the S2Si, which contains only "E"
> 
> 
Yes, in this case no need for a named tuple. 

> We can always ask the PMAP readers to read "10 events" but we should have an unique event number.
> 
> The problem is that, because S1 and S2 are read independently, it is not easy to get the same events. For example: if you tell the function to read 5 events from s1s, it will you return (for instance) events number [0, 1, 3, 7, 8], while if you do the same with s2s you get something like [0, 1, 2, 3, 4]. This can be handled by a PMapReader, that reads s1s and s2s simultaneously, but needs to be taken into account. Agreed?
> 
> 
Yes, but somehow this in inherent to the structure of the data. We can give the reader different options (including to give us the first 5 events in which S1 and S2 are present), but we still need an unique event number.
> Not stupid! This is exactly what I am proposing. We store the E samples in S2Si wether they are zeros or not, and forget about the samples!
> 
> Maybe I misunderstood you. I thought you were referring to the transient representation only. I was referring also to the persistent one.
> 
> 
Indeed, persistent one too!

**Comment by jjgomezcadenas** [comment] 2017-03-10 20:20
Following with the discussion. We discussed that read_pmaps() could return pmaps in transient form, rather than DF that map the tables. 
`I argue instead that this function should return the DFs (same as is doing now)`

Why? Because in many tests we want to read back the table and compare what is there with what we expect. Thus we need easy access to the table representation. 

Instead, we can have a PMapReader that returns only the transient representation. Thus, we can use a convenient set of classes for handling the I/O while leaving utility functions like read_pmaps() still available. BTW, the function should probably be re-baptised as read_pmpas_as_df()

**Comment by jacg** [comment] 2017-03-10 20:45
> take a look to my branch PmapWriter

First and foremost, it's so good to see this functionality extracted and isolated! If this had been available when I was trying to understand pmaps writing (and other pmaps-related concepts, and other bits of `Irene`) it would have saved me many hours!

Now, let's conisder the usage example that appears in the accompanying test

    with tb.open_file(PMP_file, "w") as pmap_file:
        pmw = PMapWriter(pmap_file)
        pmw.store_pmaps(0, S1, S2, S2Si)
        pmw.flush()

BTW, let me point out how useful it is to have this example in the test: like this I can see how it is intended to be used, rather than having to wonder. Chalk up one more point for tests-as-documentation.

[ Aside: there is a significant difference between files and their names, and I really do wish y'all would start using variable names which reflect that difference. In the above code, `PMP_file` should really be called `PMP_file_name` because it is the *name* of the file you are planning to create later on. `pmap_file` really *is* (a Python object acting as an interface to) a file, so that name is fine. ]

Having only this example of usage to go on, it seems obvious that a better interface would be

    write_pmap_file(PMP_file_name, event, S1, S2, S2Si)

But I'll assume that another valid example of usage would be 

    with tb.open_file(PMP_file_name, "w") as pmap_file:
        pmw = PMapWriter(pmap_file)
        pmw.store_pmaps(0, S1, S2, S2Si)
        pmw.store_pmaps(1, T1, T2, T2Si)
        pmw.store_pmaps(2, U1, U2, U2Si)
        # etc.
        pmw.flush()

In which case, a better inteface would be

    with pmap_writer(PMP_file_name) as write:
        write(0, S1, S2, S2Si)
        write(1, T1, T2, T2Si)
        write(2, U1, U2, U2Si)
        # etc.

Note that in both of my suggestions the manual call to `flush` disappears. If, in the second example, for some reason, you wanted to flush manually at some point, it could be done with `write.flush()`. In the first example it makes no sense to flush manually.

The second interface would, of course, also support use without `with`:

    write = pmap_writer(PMP_file_name)
    write(*this)
    write(*that)
    write.flush() # entirely optional
    write(*more)
    write.close() # mandatory

in case you need the flexibility.

There are other minor suggestions to be made, but let's deal with the meat of it first.

Is there some use case which exceeds the capabilities of the interface I suggest?

**Comment by jacg** [comment] 2017-03-10 20:53
> Following with the discussion. We discussed that read_pmaps() could return pmaps in transient form, rather than DF that map the tables.
I argue instead that this function should return the DFs (same as is doing now)

> Why? Because in many tests we want to read back the table and compare what is there with what we expect. Thus we need easy access to the table representation.

Yesterday @neuslopez and I were mulling this over. I think that we both felt (correct me if I'm wrong) that the intermediate step via dataframes between transient dicts and persistent HDF5 was useful, not only for testing, but also for separating concerns and keeping the functions simple. The user should  be presented with a single function which chains the two steps together inside a black box.

If the intermediate step through dataframes turns out to be a peformance bottleneck, then we could implement direct converters between transient and persistent storage, without the client being any wiser ... as long as we provide that black box from the start.

**Comment by jacg** [comment] 2017-03-17 08:20
>  I think that we both felt (correct me if I'm wrong) that the intermediate step via dataframes between transient dicts and persistent HDF5 was useful

I just want to record publicly that, after having worked in this part of the code, my opinion has changed drastically: I now think that we should remove the dataframes completely, if we are not exposing them as the client interface. They only seem to complicate matters.

**Comment by jacg** [comment] 2017-03-17 08:22
I am closing this as a preliminary *implementation* has been done in #171, while the discussion of the *interface* will take place in #177.

**Closed as completed by jacg** 2017-03-17 08:22 UTC

**Comment by jjgomezcadenas** [comment] 2017-03-17 09:19
>I just want to record publicly that, after having worked in this part of the code, my opinion has changed drastically: I now think that we should remove the dataframes completely, if we are not exposing them as the client interface. They only seem to complicate matters.

Also for the record, I do think they are a convenient way to load the tables in memory. If there are alternative (more efficient, cleaner) ways to do it, I am willing to eat my peras with you.
