### ISSUE TITLE
Event ID numbering in Monte Carlo

### ISSUE THREAD

**Issue by neuslopez** [next-exp/IC#145] opened 2017-03-01 09:44 UTC
The need of having unique event ID numbers for a MC production bunch.
Now we have event IDs starting at '0' for every file in the same production, therefore we cannot merge files.

**Comment by jacg** [comment] 2017-03-01 09:59
Could you write an automated test that somehow communicates this need and demonstrates the shortcoming?

**Comment by jjgomezcadenas** [comment] 2017-03-09 08:54
The point raised by @neuslopez is related with data organisation and is not obvious to me that a test is relevant here. In short, the situation is as follows:

1. Data events have a unique "event number" generated by the DAQ. This event number is extremely useful when you need to locate a particular data event. It is, so to speak, an analysis feature, a commodity.

2. MC events in IC, so far do not have a unique event number, since this number is not, as far as I know, generated by the input Monte Carlo. What we do is to give MC events a number associated with the position of the event in the set of input files that are processed by IRENE. But as a consequence, next time we process a different bunch of files, the numbers repeat. This is not good.

The best solution for this would be that event numbers are propagated to us from NEXUS. That should be possible, no? Please @paolafer, @neuslopez, @jmbenlloch, say your opinion.

Alternatively, we can call a random number as a seed each time we process a bunch of files and create a "unique event number"  (although then we need bookkeeping to ensure that there are no repetitions).

The issue is not trivial, since presumably we will find events we want to isolate and study/reprocess. Thus we need to settle it. 

The need to carry the event_DAQ as unique identifier of the PMAP is another related issue. Notice that in the current implementation (@jacg, @gonzaponte), we are returning:

{event: {peak: ([t], [E])}

But we use as reference for "event" the field "event" in the tables:

class S12(tb.IsDescription):
    """Store for a S1/S2
    The table maps a S12:
    peak is the index of the S12 dictionary, running over the number of peaks found
    time and energy of the peak.
    """
    event  = tb.Int32Col(pos=0)
    evtDaq = tb.Int32Col(pos=1)
    peak   = tb.UInt8Col(pos=2)  # peak number
    time   = tb.Float32Col(pos=3) # time in ns
    ene    = tb.Float32Col(pos=4) # energy in pes

This is fine if we work with a bunch of PMAPS derived from a single "file bunch" processing, but would result in repeated keys (for event) if we merge to PMAPS files. Thus, the key must be evtDAQ, not event (in fact I believe that we just need one field and it must be what we call evtDaq, do you agree, @jmbenlloch?) 

This will work fine for data, for MC we need to get or generate a unique number. To repeat, can we send already a unique number from NEXUS @paolafer?

**Comment by paolafer** [comment] 2017-03-09 09:02
In nexus IDs are assigned to events. In the existing files, IDs starts from 0 in each file (so numbers can repeat), but there is also the possibility of assigning a different event ID for each event along a given production.
Caveat: since in nexus we save only those events that deposit something in the active volume, there may be missing IDs (it's not 0, 1, 2..., but rather 0, 3, 8...), but I don't think that's a problem for you.

**Comment by jacg** [comment] 2017-03-09 16:21
Would a UUID be useful here? If you follow stardards, it would cost 128 bits each. Otherwse a smaller random number might do, or a hash of the data. How many of these are you expecting in the same 'namespace'?

**Comment by jjgomezcadenas** [comment] 2017-03-09 18:10
For a given processing order 10^6 events per chunk (“name space”), I would say. Do you agree, @jmbenlloch?

**Comment by jmbenlloch** [comment] 2017-03-09 18:21
Yes, for a given MC run, about 10^6 events.
But I think using consecutive numbering is useful since it would allow us to track an event easily. We have 10k events per file in the first step (MCRD). If later on, somebody is working with, for instance, PMAPS, knowing the event number automatically tell us in which file we can find the corresponding waveforms (file 1 from evt 0 to 9999, file 2 from 10000 to 19999, etc.).

**Comment by jjgomezcadenas** [comment] 2017-03-10 09:31
In short, we need a scheme to produce unique run numbers and event numbers for the MC. MC run numbers will be negative by definition. Event numbers can be produced directly by DIOMIRA, or more in general by a MCCity which may take care of this. We need to discuss how to do it, but the need is clear.

**Comment by paolafer** [comment] 2017-03-10 09:34
Hi! I didn't follow the discussion, so maybe this is not relevant, but in
art we set the MC run number in a way that is related to the values of
calibration database that we use in the production of the signals. It is a
way of using the values in the database for the run we want.

Il giorno ven 10 mar 2017 alle 10:31 jjgomezcadenas <
notifications@github.com> ha scritto:

**Comment by jacg** [comment] 2017-03-15 17:59
Done in #168.

**Closed as completed by jacg** 2017-03-15 17:59 UTC
