### ISSUE TITLE
Failure in tests

### ISSUE THREAD

**Issue by paolafer** [next-exp/IC#263] opened 2017-07-03 11:08 UTC
One of tests is failing in my Mac, namely 

invisible_cities/reco/sensor_functions_test.py::test_cwf_blr[electrons_40keV_z250_MCRD.h5]

with the following error:

E           assert 1.7658670951263973 < 1
invisible_cities/reco/sensor_functions_test.py:47: AssertionError

Any idea of what the reason is, @jjgomezcadenas ?

**Comment by jjgomezcadenas** [comment] 2017-07-03 13:12
The test checks that the result of the convolution + deconvolution is equal (within tolerance) to the original waveform. The problem can be fixed increasing the tolerance, but I don't understand why the test passes everywhere except in your Mac.

**Comment by Aretno** [comment] 2017-07-10 08:21
I have updated my master to the latest repository and I'm having the same issue Paola has with this same test.

**Comment by jjgomezcadenas** [comment] 2017-07-20 07:41
Do you still have this problem, @paolafer , @Aretno ?? It is not showing up anywhere else

**Comment by Aretno** [comment] 2017-07-20 08:43
Yes, I have. I think @jahernando also had this issue. I tipically get "assert" values between 3-5.

**Comment by jjgomezcadenas** [comment] 2017-07-20 10:51
This is very funny. It never appears in my local or in TRAVIS. Not sure what is best here.

**Comment by jerenner** [comment] 2017-07-20 10:55
I am also getting a failed test on my Mac with invisible_cities/reco/sensor_functions_test.py:47: AssertionError with: 
E           assert 3.992222624122006 < 1

**Comment by jjgomezcadenas** [comment] 2017-07-20 11:04
I cannot reproduce this error locally. Are u running the last version of the code?

**Comment by jerenner** [comment] 2017-07-20 11:06
I got the error this morning when running the code on Alex's branch debug-cities

**Comment by jmbenlloch** [comment] 2017-07-20 12:30
Maybe is some old binary file (pyc or whatever), you could try running: `bash   manage.sh clean` and then `source manage.sh work_in_python_version 3.6` again.

**Comment by Aretno** [comment] 2017-07-20 13:43
No improvement on my side with the cleaning.

**Comment by jerenner** [comment] 2017-07-20 13:46
The cleaning does not seem to help for me either

**Comment by jacg** [comment] 2017-08-30 16:18
What is the status of this? Are these tests still failing for anyone?

**Comment by Aretno** [comment] 2017-09-01 11:21
It still does for me. I think @jmbenlloch also saw these tests failing in Canfranc computers.

**Comment by jacg** [comment] 2017-09-01 11:38
I suggest that you move your conda installation out of the way (`cp $HOME/miniconda $HOME/miniconda.moved-away`) and then do a full `source manage.sh install_and_check 3.6` in a fresh shell)

This should tell us whether its caused by some feature of your machine, or some feature of your existing conda state.

Same for #299.

**Comment by Aretno** [comment] 2017-09-01 12:55
Indeed it seems it was something in my conda, now this tests and those of #299 seem to be fixed. However I have a new one:

```
_______________________________________________________________________________________ test_in_range_right_shape ________________________________________________________________________________________

    @given(random_length_float_arrays(max_length = 1000))
>   def test_in_range_right_shape(data):
E   hypothesis.errors.FailedHealthCheck: Data generation is extremely slow: Only produced 9 valid examples in 1.07 seconds (0 invalid ones and 0 exceeded maximum size). Try decreasing size of the data you're generating (with e.g.average_size or max_leaves parameters).
E   See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.too_slow to the suppress_health_check settings for this test.

invisible_cities/core/core_functions_test.py:64: FailedHealthCheck
=========================================================================== 1 failed, 295 passed, 1 skipped in 135.28 seconds ============================================================================
```

**Comment by jacg** [comment] 2017-09-01 13:08
Does this happen consistently, or have you tried it only once?

**Comment by Aretno** [comment] 2017-09-01 13:15
No, I checked right now and it does it randomly. I suppose it's because I have the PC overloaded with stuff. One thing to note is that I had anaconda installed instead of miniconda, maybe other users experimenting this issue also had anaconda.

**Comment by gonzaponte** [comment] 2017-09-01 13:19
I don't know if you remember, @jacg, but when we were testing the module `fit_functions.py` we found that hypothesis had problems with generating "big" arrays. We found the limit to be 1024 elements. This might have changed in recent releases, but I haven't found yet anything in the [changelog](https://hypothesis.readthedocs.io/en/latest/changes.html), although there have been a few twiches to the numpy section of hypothesis.

**Comment by jacg** [comment] 2017-09-01 13:30
> I suppose it's because I have the PC overloaded with stuff.

If you mean that it is running lots of other things at the same time, then that could well be the case. The health check merely signals that hypothesis is struggling to come up with valid examples in a reasonable amount of time.

@gonzaponte Yes, I remember, but I don't see what that could have to do with the current case. This particular test has a hard limit of 1000, so we cannot exceed that. If we did, we wouldn't get a health check, we'd get a different kind of error.

If you look at the error message, you'll see that hypothesis managed to come up with only 9 examples of 1000-length arrays in 1s (with no rejections or other problems)! It's just running extremely slowly.

@Aretno Can you run it sometime when your machine is otherwise idle, please? It should simply not happen in normal circumstances: this test is not asking hypothesis to come up with anything particularly difficult.

**Comment by jacg** [comment] 2017-09-01 14:01
> One thing to note is that I had anaconda installed instead of miniconda, maybe other users experimenting this issue also had anaconda.

Unlikely (but not impossible).

Miniconda and anaconda are essentially the same thing, the main difference is that miniconda installs a bare minimum of packages at the beginning, and then you can install extra ones as you need them. Anaconda assumes you are going to need just about every package in existence and installs millions of them during the initial install. Apart from that, its the same packages, installed with the same manager. So it's unlikely that that was the problem.

It's more likely to have been caused be some older version of something that was lying around getting in the way of something else.

**Comment by Aretno** [comment] 2017-09-01 14:23
Yes, I meant running several things at once, I'll try to run the tests again when I'm not running anything else and let you know, thanks!

**Comment by jacg** [comment] 2017-09-07 22:26
Here's another example of why we need @307.

**Closed as completed by jacg** 2017-09-07 22:26 UTC
