### ISSUE TITLE
Error installing magit in Mac 10.10.2

### ISSUE THREAD

**Issue by paolafer** [next-exp/IC#109] opened 2017-01-30 13:51 UTC
We have been trying to configure magit in Paola's emacs but it doesn't work. This is the error we are getting:

```
Warning (el-get): Your Emacs doesn't support HTTPS (TLS).
Warning (el-get): Failed to retrieve emacswiki package list: .
Warning (initialization): An error occurred while loading `/Users/paola/.emacs':

Symbol's value as variable is void: package-archive-contents

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
```

Any idea how to solve that?

**Comment by jjgomezcadenas** [comment] 2017-01-30 14:06
It may well be that Paola does not have the standard emacs 24, but some variant for the Mac OSX. 

If you don’t have it, try this version:

https://emacsformacosx.com/ <https://emacsformacosx.com/>

And download last version (25). 
J

**Comment by paolafer** [comment] 2017-01-30 14:14
We have tried in neutrinos and we get a similar error:
```
Error (el-get): while installing dash: Symbol's function definition is void: string-prefix-p
Error (el-get): while installing with-editor: Symbol's function definition is void: string-prefix-p
Error (el-get): while installing emacs-async: Symbol's function definition is void: string-prefix-p
Error (el-get): while installing magit: Package magit requires Emacs version 24.4 or higher, but the current Emacs is only version 23.1.1
Error (el-get): while installing helm: Symbol's function definition is void: string-prefix-p
Error (el-get): while installing helm-ag: Symbol's function definition is void: string-prefix-p
Error (el-get): while installing helm-swoop: Symbol's function definition is void: string-prefix-p
Warning (initialization): An error occurred while loading `/home/paolafer/.emacs':

File error: Cannot open load file, package

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
```

We are going to update emacs to the last version.

**Comment by jjgomezcadenas** [comment] 2017-01-30 14:20
Read the message! It says:

> On 30 Jan 2017, at 15:14, Paola Ferrario <notifications@github.com> wrote:
> 
> 
> 
> Error (el-get): while installing magit: Package magit requires Emacs version 24.4 or higher, but the current
> 

Try in your Mac (and in neutrinos) version 24.4 or higher (and in the case of MAC use the link I sent you).

**Comment by paolafer** [comment] 2017-01-30 14:47
In my Mac it works. @jmbenlloch  is going to update emacs in neutrinos.

**Comment by jjgomezcadenas** [comment] 2017-01-30 14:49
Good! Close issue then!

**Comment by jacg** [comment] 2017-02-01 16:33
Has this issue been resolved?

If so, please close it!

**Comment by paolafer** [comment] 2017-02-01 18:14
Not yet! We have to fix it in the neutrinos cluster.

**Comment by jjgomezcadenas** [comment] 2017-02-01 18:15
Yes, but the issue is the same, the version of neutrinos was obsolete, so the issue can be closed. Reopen if needed.

**Closed as completed** 2017-02-01 18:15 UTC
Labels: bug, help wanted
