### ISSUE TITLE
Current version of Dorothea awfully slow

### ISSUE THREAD

**Issue by gonzaponte** [next-exp/IC#309] opened 2017-08-30 12:04 UTC
The current version of Dorothea is running very slowly. I have compared the timing between this version and the (very) old and stable version we use by default. The outcome for 100k events:
old version: 146.9 s
new version: 742.8 s (5x slower!)

This is making the data processing very tedious. I guess this somehow goes back to the big refactorization of the cities.

**Comment by jacg** [comment] 2017-08-30 12:19
Can I perform such a run with data available in our repo?

**Comment by gonzaponte** [comment] 2017-08-30 12:24
We have a few pmaps in database/test_data/KrMC_pmaps.h5, but I don't know if that is enough for timing purposes.

**Comment by jjgomezcadenas** [comment] 2017-08-30 12:47
This issue brings up two different questions.

1. Providing data not in the repository. This is needed for instance when we want to run with large files. We can use the gallery (e.g, our http server at neutrinos), or a shared space in our servers (e.g, neutrinos). We would need to open an account for @jacg in neutrinos but this is trivial. What do you prefer? (solutions are not mutually exclusive).
2. We need to time what is going on in Dorothea. The refactoring itself is very unlikely to have created such a slow-down. There must be *something* very specific slowing down the code that should be "easy" to find. 

Can I assign solving this issues to @gonzaponte @jacg ?

**Comment by gonzaponte** [comment] 2017-08-30 12:49
it is fine with me

**Comment by jacg** [comment] 2017-08-30 13:06
> Providing data not in the repository. This is needed for instance when we want to run with large files. We can use the gallery (e.g, our http server at neutrinos), or a shared space in our servers (e.g, neutrinos). We would need to open an account for @jacg in neutrinos but this is trivial. What do you prefer? (solutions are not mutually exclusive).

LFS!

(At a reasonable price scheme: we'll have to check how the landscape has evolved since I looked into this a few months ago.)

**Comment by jacg** [comment] 2017-08-30 13:20
I'm happy to be assigned, as long as you realize that the time I have available for IC will be very sporadic in the coming weeks/months, so don't expect anything to happen any time soon.

**Comment by jjgomezcadenas** [comment] 2017-08-30 13:26
@gonzaponte should take the lead on this since Dorothy is her girl. But he can always use the support of the master.

**Comment by jacg** [comment] 2017-08-30 13:30
Please give me the command I should issue to get the longest Dorothea run I can get with what is currently in the repo.

**Comment by gonzaponte** [comment] 2017-08-30 13:38
`city dorothea $ICDIR/config/dorothea.conf`

**Comment by jacg** [comment] 2017-08-30 13:44
Yup ... which takes the `KrMC_pmaps.h5` file you mentioned earlier, which runs 10 events in about 0 seconds ... so I'll need a bit more to work with.

**Comment by jacg** [comment] 2017-08-30 13:51
Do we have *anything* in the repo that will allow me to run *any* city for 10 seconds or more?

**Comment by gonzaponte** [comment] 2017-08-30 13:59
I don't think so. The files we have in the repo are there so we can run tests, but since we don't need many events for that, the files are filled with the minimal amount of data.

**Comment by jjgomezcadenas** [comment] 2017-08-30 14:11
As a temporary fix, @gonzaponte can you put the file you used for your Dorothy tests somewhere accessible to @jacg ?

**Comment by gonzaponte** [comment] 2017-08-30 14:29
Yes, is a link to google drive (or a similar service) ok? I can share a password-protected zip file with the data.

**Comment by jacg** [comment] 2017-08-30 17:00
Should work.

**Comment by gonzaponte** [comment] 2017-08-30 17:16
https://drive.google.com/open?id=0B5Om0RlXo1xGOUtKVUpUaGJLdWc

**Comment by jacg** [comment] 2017-08-30 17:36
Got it. How should I use these? I tried feeding one of them to Dorothea, and got

    sqlite3.OperationalError: no such table: ChannelGain

**Comment by gonzaponte** [comment] 2017-08-30 17:38
Mmm. Have you updated the database? You should also use run_number 4446, just in case.

**Comment by jacg** [comment] 2017-08-30 17:48
The problem was caused by me having checked out the `git-lfs` branch in the meantime, which got me an old version of the database.

What is the exact command I should give? It now runs, but under 2 seconds.

**Comment by gonzaponte** [comment] 2017-08-30 17:53
`city dorothea $ICDIR/config/dorothea.conf -r 4446 -i 'data_jacg/*' -o outputfile.h5` should work. But ***first*** you need to change nmax to -1 in the configuration file, because the command line option is not working.

Edit by @jacg: added quotes around `data_jacg/*`.

**Comment by jjgomezcadenas** [comment] 2017-08-30 21:19
Quick suggestions. Check event_index in the tables... in for some reason we have forgotten to index the tables in the pmaps writers, Dorothy will run much slower..

**Comment by gonzaponte** [comment] 2017-08-30 21:24
Ok, we need to fix that and reprocess then. It will have a big impact, for
sure.

**Comment by jacg** [comment] 2017-08-30 21:26
> But first you need to change nmax to -1 in the configuration file, because the command line option is not working.

Which means that the command line options need to be fixed first. Let's see if I can find the time to do it tomorrow.

**Comment by gonzaponte** [comment] 2017-08-31 08:59
> Let's see if I can find the time to do it tomorrow.

I can work on it, if you want.

**Comment by jacg** [comment] 2017-08-31 09:08
I'll have a couple of hours this afternoon to try to come up with some sensible tests.

**Comment by jacg** [comment] 2017-08-31 09:11
> I'll have a couple of hours this afternoon to try to come up with some sensible tests.

Errm, sorry, forget that, wrong issue! I'll try to write some tests for #307.

**Comment by gonzaponte** [comment] 2017-08-31 11:03
> Quick suggestions. Check event_index in the tables... in for some reason we have forgotten to index the tables in the pmaps writers, Dorothy will run much slower..

I have checked that the tables are indexed. In `pmap_io.py ->  _make_pmp_tables`:
```
    for table in pmp_tables:
        table.cols.event.create_index()
```

So it must be something else, I am trying to figure it out.

**Comment by jacg** [comment] 2017-09-09 13:34
> The outcome for 100k events:
> old version: 146.9 s
> new version: 742.8 s (5x slower!)

So that's 0.0015 s / event -> 0.0075 s / event.

I'm on a different machine, so we can't compare these directly, but the current version run on the 17000 events in the files you sent me, gives me 0.0017 s / event. IOW, I don't seem to be able to reproduce the problem here.

**Comment by jjgomezcadenas** [comment] 2017-09-16 07:22
Any further insight here, @gonzaponte ?

**Comment by jacg** [comment] 2017-10-12 06:27
It would have been nice to have some feedback from @gonzaponte before closing this.

**Comment by gonzaponte** [comment] 2017-10-12 09:30
@gonzaponte doesn't have time to look at this right now, but it can remain open until I do. It seems having open issues/PRs in github is itself an issue.

**Comment by jacg** [comment] 2017-10-12 09:38
> It seems having open issues/PRs in github is itself an issue.

On the one hand, it is good to go through stale issues and close those which can be closed sensibly. On the other hand, some people are a bit too trigger-happy in this process. (I wonder whether such people associate open issues with bad karma?)

**Comment by jjgomezcadenas** [comment] 2017-10-12 09:54
Man used to drink a good single malt late at night, for happy dreams, now he's dry like a desert. Guess he gets some pleasure out of issues closing, specially at small hours. He just meant well, though, trying to cut the pile shorter. Otherwise the list becomes so long that one stops looking at issues... or so he says.

**Comment by jacg** [comment] 2017-10-12 10:31
It is *important and worthwhile* to close stale issues that need closing. As you say, one negative consequence is that a long list of open issues just encourages you to ignore them all.

But the process of closing them must *discriminate* between those that really should be closed, and those that need to remain open.

**Comment by jjgomezcadenas** [comment] 2017-10-12 10:50
Agreed, late night bouts are kind of dangerous. Apologies

**Comment by jacg** [comment] 2018-07-28 12:00
That was 8 months ago. Given how stale this is and how unlikely it is that it will be picked up, I'd rather close it than have it contribute to flooding our project board.

**Closed as completed by jacg** 2018-07-28 12:00 UTC
