### ISSUE TITLE
Hard and Soft reviews. 

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#373] opened 2017-10-11 20:36 UTC
In today's analysis meeting a proposal has been made to start introducing some sense in the development of analysis. Remember that analysis is mostly run by notebooks living in ICARO. So far, it has been a jungle. We are trying now to introduce some sense.

Analysis will still be formulated in NBs since their ability to put together code and plots is really useful. Different analysis will go to different branches (Kr, Tl, Monitoring, etc.) with a common directory structure. We have agreed that developers will open PRs to commit NBs in the central ICARO repo. We have also agreed that NBs will be as bare as possible.

"Bare" means that the NB will mostly call external functions and produce plots and fits. A NB is only authorised to keep a function if it is specific of that NB (e.g, no one else is a potential client). Functions with more clients (e.g, plotting functions and all sort of utility functions) should instead go to *IC* in particular to the *ICARO* directory in IC. 

In fact, some of us, in particular @gonzaponte and yours truly have already been working like this for a while and IC/ICARO contains a substantial number of plotting and utility functions. All those functions have gone through PR and approved, but often enough the reviewer has been merciful.

In fact, the consensus in today's analysis meeting was that it is, indeed, a good idea to be merciful with IC/ICARO PRs. The rationale is that the level of reviewing can be different for PRs that affect *reconstruction* or *software structure* and PRs that affect *analysis*.

As an example: Mistakes in a PR related with a city that processes data has a sore price in lost processing time and general confusion. A mistake in a plotting function is almost irrelevant, the users will catch it and correct it quickly since those functions are continuously being exercised in the analysis NBs.

However, *I have insisted that it is a good policy to PR those plotting functions to IC/ICARO* so that a reviewer can look at them and suggest improvements, etc. Also, if the plotting functions are left in the Notebooks we end up with 500 different versions (each developer ends up writing seven versions of the same plotting function in seven different notebooks). By putting them in IC/ICARO we can collect them, try to avoid duplications and eventually make them better.

Nonetheless if we want that people working in analysis PRs their analysis functions to IC/ICARO rather than leaving them in their NBs (or putting them in python scripts in their areas) we need a more agile review policy for analysis stuff. Analysis simply moves too fast while the IC reviews tend to be rather slow. 

Thus, I wanted to propose the possibility to call for *express review* in the case of PRs that affect IC/ICARO. Express review simply means that the reviewer tries to go as fast as possible. **The need to add a test for each function still applies**, with the exception of plotting functions, which, as mentioned, are naturally tested by use and too hard to test canonically. So express review is not a blank check for untested or lousy code, but the reviewer may decide to strike a compromise so that needed code get into the loop quickly. 

Please comment.

**Comment by jacg** [comment] 2017-10-13 06:38
> A mistake in a plotting function is almost irrelevant, 

That's a very cavalier statement!

> the users will catch it and correct it quickly since those functions are continuously being exercised in the analysis NBs.

... or they won't realize the plot is wrong; and they'll waste a lot of time on believing the nonsense that they've been looking at.

Anyway, I am in danger of producing a voxel / track visualizer, as a byproduct of something I am doing outside of IC. Where should I put this code?

**Comment by jjgomezcadenas** [comment] 2017-10-13 07:03
Or perhaps I am trying to choose the laser evil. If we insist that people working in analysis have to add tests to their plot functions, then they will simply keep them in their NBs and the consequence will be a proliferation of the same thing over and over. On the other hand,  I have almost never seen a function producing a wrong plot tricking me. Generally when you try to plot something is all very straight forward and most of the work goes to mundane details such as axis and labels. I am not making cavalier's statements but building on experience, after more than one year development on IC.

Right now, we are doing things acceptably well, perhaps, in the reconstruction code (thanks largely to you, not to forget your Galician acolyte). But everyone working in analysis is just messing around, duplicating code and developing totally out of control. This must be improved. But given the cycles of analysis and the resource we have, we simply cannot keep the same standards for analysis and for reconstruction.

Nor is needed. A plot is a plot is a plot. You need fifty test to be sure you are deconvolving well your waveforms, everything else depends on it. Instead, if the label of your final plot floats too much, the amount of tragedy is limited.

**Comment by jjgomezcadenas** [comment] 2017-10-13 07:04
>Anyway, I am in danger of producing a voxel / track visualizer, as a byproduct of something I am doing outside of IC. Where should I put this code?

In IC/ICARO. BTW, I did produce some (surely inferior, nasty and despicable) versions of voxels and track visualisers months ago. So, here is an example of how, by putting stuff in IC/ICARO we can improve...

**Comment by jacg** [comment] 2017-10-13 07:29
There is a world of difference between 'insisting that people working in analysis have to add tests to their plot functions' and acknowledging that 'a mistake in a plotting function is almost irrelevant' is indeed a cavalier statement.

> But everyone working in analysis is just messing around, duplicating code and developing totally out of control. This must be improved.

Absolutely agreed.

> we simply cannot keep the same standards for analysis and for reconstruction.

I agree completeley. And yet I stand by my original statement.

If you are after two different levels of review, I wonder whether ICARO should be a separate repository that uses IC as a submodule. That way the boundary remains clear. I'm very hazy on the details, but I seem to recall that ICARO was a separate repo for a while.

I would prefer for IC to continue maintaining the standards we have tried to establish there, and i would prefer for IC to remain blissfully ignorant of ICARO: ICARO is a client of IC, not the other way around.

>> Where should I put this code?

> In IC/ICARO.

Well ... yes .... but where? Is there some structure there, some organizational principle? Or do I just pick any name I like and dump it in `icaro/`?

> I did produce some [...] versions of voxels and track visualisers months ago.

Which admirably demonstrates the point about the need to upload these things into an ICARO repo.

The duplication (mega-multiplication) of code and effort must be a *huge* sink of Next resources!

In case anyone is still reading: **The point @jjgomezcadenas is making in this issue is vitally important.** For your own sakes, take it seriously, give it some thought, and contribute to the discussion and resolution.

**Comment by jjgomezcadenas** [comment] 2017-10-13 07:47
>If you are after two different levels of review, I wonder whether ICARO should be a separate repository that uses IC as a submodule. That way the boundary remains clear. I'm very hazy on the details, but I seem to recall that ICARO was a separate repo for a while.


Nooo!! God forbids! As soon as we step out of IC, we are doomed. Before you knew it, people would be back using root. Let's keep the stuff in IC, let's try to do our best, let's compromise!!! No unilateral declaration of independence please, no new Free Socialist Republic of ICARO where marijuana is free and reviewers are all sold out to the gold of Moscow.

**Comment by paolafer** [comment] 2017-10-13 07:55
> For your own sakes, take it seriously, give it some thought, and contribute to the discussion and resolution.

I'd be happy to contribute, can you just clarify the main point of the discussion? Is it whether to create a different repository for ICARO or putting it inside IC?

**Comment by jjgomezcadenas** [comment] 2017-10-13 07:56
>I would prefer for IC to continue maintaining the standards we have tried to establish there, and i would prefer for IC to remain blissfully ignorant of ICARO: ICARO is a client of IC, not the other way around.

Actually, there are two ICAROS (sorry, just to keep the enemy confused). ICARO as a repository is the place where people runs their notebooks for analysis. It is a very happy place, sex and drugs are free and you can lie around the beach most of the time. You lump all your code in Notebooks which you duplicate randomly and frequently. ICARO is indeed a client of IC. A drunk client, for that matter, but still a client. 

**BUT** we are now trying to put some order there. Just enough so that you can walk the streets without sleeping in the spilled liquor. The idea is that Notebooks loose some of their fat, delegating functions that are general enough as to be useful for everybody else to some other place.

The original proposal was to put those functions also in ICARO. **I opposed to that and I still oppose, fervently**. It was simply an attempt of a coup. Let's put the stuff in ICARO, so that the master never gets the chance to see it and point HIS finger at us. NO!!!

There is another ICARO, a directory that leaves in IC, where all kind of useful functions for analysis are placed. The functions that go to ICARO are tested, and the standards are not horribly low (perhaps with the exception of the plotting stuff). 

I really insist that all the good stuff that is developed for analysis (and there is plenty) goes there. In this ways, ICARO (the notebook analysis happy place where you can surf all day and lie in the beach at night) is still the IC client, more so because all intelligent stuff is there. And IC know not about the analysis ugly details, as you wish.

**Comment by jacg** [comment] 2017-10-13 07:58
WTF!?!? Root? What are you talking about?

Of course there would be a review process in ICARO: the *soft* review in the title of this issue. And a standard part of that soft review would be a **hard** rejection of anything that uses Root on any other inadmissible evil. ICARO should be an IC-based analysis repository.

The central part of my message is that ICARO should depend on IC, and IC should be independent of ICARO.

**There should be no knowledge of ICARO in IC.**

IC is a reconstruction framework, ICARO is a set of analysis tools. Analysis depends on reconstruction, reconstruction **does not** depend on analysis. What am I missing?

**Comment by jacg** [comment] 2017-10-13 08:03
Sorry, I really do have other things to be doing right now ... so I don't have time to go over details right now.

Let me just reiterate the fundamental principle:

**Reconstruction does not depend on analysis, so there should be no hint of analysis code in the reconstruction framework's repo.**

If you go against this principle, weird stuff is going to start creeping up on us, and then, many months down the line, I'll get to say "I told you so! I told you so!" ... which would be far less satisfying and productive than avoiding the weird stuff in the first place.

**Comment by jjgomezcadenas** [comment] 2017-10-13 08:03
>I'd be happy to contribute, can you just clarify the main point of the discussion? Is it whether to create a different repository for ICARO or putting it inside IC?

See what happens? @paolafer  has spent too much time in ICARO beach and not enough in IC factory.

The main point of the discussion is to implement the strategy suggested at the analysis meeting two days ago. To clarify again:

1. ICARO is an analysis repository which depends on IC. The main objects there are Notebooks.
2. Notebooks tend to proliferate, typically duplicating code, as they are creatures created in haste and rage. 
3. After a few weeks of working on Notebooks, one typically identifies functions which really do not belong there. They are fits, utilities, classifiers, plots, stuff like this. They could be put in a different repository, but why? We can put them where there is already stuff like this, that is IC/ICARO.
4. The only point I dared to rise was to be slightly more tolerant for reviews with such stuff (as a general rule). The stuff still should come with tests (except, for now, I argue, plots), but we could try to express-review, so that the analysis cycle is fat. 
5.  *I still want to keep standards*. It is a must. We have been lifted to light by standards. I don't want to descent back to the pre-IC darkness.
6. But if we don't find a compromise, people will simply leave their stuff in the notebooks, stuff will duplicate and never improve.

There must be some way in-between.

**Comment by jacg** [comment] 2017-10-13 08:07
> There must be some way in-between.

Fine, treat the current ICARO repo as a nursery, from which successful useful stuff can be taken, cleaned up, and promoted to ICARO-adult, but, please, for the love of all that is good, do not stick client code in the repository of the provider.

**Comment by jjgomezcadenas** [comment] 2017-10-13 08:08
>Reconstruction does not depend on analysis, so there should be no hint of analysis code in the reconstruction framework's repo.

What do you call analysis code? Is a plot analysis code? or a pretty-print utility? or a fit function? 

I don't think there is such thing as analysis code. Analysis code is just the tale told by an idiot, full of sound and fury, meaning... whatever it means, but the tale itself is ugly and this is why is kept in a notebook.

The *pieces* used to tell the tale are a different story. They are often bona fide stuff, functions that can be encapsulated and tested. What is wrong about them leaving in their module within IC?

**Comment by jjgomezcadenas** [comment] 2017-10-13 08:09
>do not stick client code in the repository of the provider.

OK, this is a good rule of thumb. The review should make sure of that.

**Comment by jjgomezcadenas** [comment] 2017-10-13 08:11
BTW. In hvt_mpl.py (in IC/ICARO) you find my poor attempts at plotting functions (tracks, voxels and such). They are pretty ugly, but last time I tried they worked. Decent plotting is a different story, BTW, that we need to address some time.

**Comment by jacg** [comment] 2017-10-13 09:12
> A mistake in a plotting function is almost irrelevant, the users will catch it and correct it quickly since those functions are continuously being exercised in the analysis NBs.

Let me present an argument to convince you that this is claim is fundamentally flawed.

The claim assumes that there is some user who is actively and continuously using the plotting function. What happens if nobody has been using the function for a few weeks or months? What happens if other things on which it relies have changed in a way that breaks the function? What happens if the user wants to use the function after a period of not having used it, and comes back to find it broken? He now wastes time on figuring out whether the errors are caused by something he is doing wrong, or whether they come from elsewhere.

Or, perhaps, tracing the problem to its root seems like too much hard work, and he decides that it's easier to write his own. (You want to stop people from doing that, remember?)

What happens if nobody is using the function at all? [Remember, you claim that the function is adequately tested by users using it: so this function is effectively untested.] Now, someone sees the function in the repo and wants to start using it. It doesn't work, so the poor user blames himself: after all, if it's in the repo, it must work correctly, right? So he looks for the test which will provide an example of the function's usage that is guaranteed to work ... only there is no such test.

What happens if a developer changes a utility on which the function relies, in a way that breaks the function? Without an **automated** test, the developer has no clue that anything has gone wrong, and neither do the reviewers. This problem which should be nipped in the bud, instead gets approved, merged, and dumped in the lap of the poor user whose plotting function suddenly stops working. Do you want to deal with this in the small hours of the night before the important presentation you are desperately trying to finish off?

I think you have come a long way, in the last 10 months, along the path to understanding the vital need for **automated** tests. But you still have a fair way to go.

To illustrate that the above arguments are not purely theoretical: I have just wasted some time on trying to see your `hvt_mpl.py` utilities in action. With no tests to guide me as to how they are used, I came up with some inputs, tweaked them in response to the errors I got, and gave up after the nth mysterious error deep inside your code.

Given that removing the whole module does not cause a single test in our test suite to fail, I have absolutely no confidence in the code, and therefore decline to waste any more of my (precious and currently very oversubscribed) time on trying to use it.

I have no idea whether you (or anyone) is using this stuff in their notebooks. If nobody is, then it's completely untested. If somebody is, then it's completely useless to me, in my attempts to get it to work.

**Comment by jjgomezcadenas** [comment] 2017-10-13 09:40
> Let me present an argument to convince you that this is claim is fundamentally flawed.

Agreed, you have a point. The problem is that automated tests seem to be a very hard to add to plotting functions. 

Methinks we need a IC-wide discussion to understand how to organise the analysis...

**Comment by jacg** [comment] 2017-10-13 10:37
> The problem is that automated tests seem to be a very hard to add to plotting functions.

Not so!

I have shown how it can be done in #119.

Any utility worth including should be accompanied by at least one (preferably several) simple example of its usage. The example should produce an image, and that example source along with the resulting image can be used to make a test à la #119.

There's no point in having these utilities in the repo if they are a secret or if it is difficult to find one that matches your needs. So we need something like the [matplotlib gallery](https://matplotlib.org/gallery.html). Each image in that gallery is a link to a page containing the source code that generates the image. As stated above, source code and image together essentially form a test: the cost of wrapping them up in an automated test is but a small overhead on top of creating them in the first place. And I trust that you agree that they are needed in the first place.

**Comment by jacg** [comment] 2018-07-28 13:42
No activity here for 9 months. Has anything become clearer? Is this going anywhere? Is there any point in keeping this open? I'll close it to reduce the noise on our shiny new workflow project board. Feel free to re-open it, if you think it would be useful to have it open.

**Closed as completed by jacg** 2018-07-28 13:42 UTC
Labels: enhancement, question
